/**
 * High-level satellite state and propagation entrypoints used by UI code.
 *
 * This module loads TLE data, initializes SGP4 precomputed terms once per satellite,
 * and exposes a convenience function that returns the current geodetic position for rendering.
 */
import tleText from '../../tle-data/visual.tle?raw'
import { eciToGeodetic, toJulianDate } from './astroUtils'
import { sgp4Init, sgp4Propagate } from './sgp4'
import { parseTle, readAllTles, type TleData } from './tleParser'

const MINUTES_PER_DAY = 1440

export type SatelliteState = {
  /** NORAD catalog number from TLE line 1; stable React list key. */
  id: string
  name: string
  tle: TleData
  p: number[]
}

/**
 * Builds initialized satellite state for every three-line entry in the TLE file.
 *
 * @returns Parsed TLE plus SGP4 initialization array per satellite.
 */
export function initSatellites(): SatelliteState[] {
  return readAllTles(tleText).map((entry) => {
    const tle = parseTle(entry.line1, entry.line2)
    const p = sgp4Init(tle)
    const id = entry.line1.trimStart().slice(2, 7).trim()
    return { id, name: entry.name.trim(), tle, p }
  })
}

/**
 * Propagates the satellite to the requested time and converts to geodetic coordinates.
 *
 * Time is taken from `date` in UTC (via `toJulianDate`), which matches standard
 * SGP4 usage; there is no extra timezone offset applied in this function.
 *
 * @param tle Parsed Two-Line Element orbital data.
 * @param p Precomputed SGP4 state generated by `sgp4Init`.
 * @param date Target moment for propagation. Defaults to current time.
 * @returns Current latitude/longitude/altitude, or `null` when propagation fails.
 */
export function calculatePosition(
  tle: TleData,
  p: number[],
  date: Date = new Date(),
): { latitude: number; longitude: number; altitudeKm: number } | null {
  const jd = toJulianDate(date)
  const tsince = (jd - tle.epoch) * MINUTES_PER_DAY
  const eci = sgp4Propagate(tsince, tle, p)

  if (eci[0] === 0 && eci[1] === 0 && eci[2] === 0) {
    return null
  }

  const geodetic = eciToGeodetic(eci, jd)

  return {
    latitude: geodetic.latitude,
    longitude: geodetic.longitude,
    altitudeKm: geodetic.altitudeKm,
  }
}
